services:
  app:
    image: ${APP_IMAGE}:${APP_TAG}
    container_name: hello-app
    restart: unless-stopped
    ports:
      - '127.0.0.1:3002:5173'
    networks:
      - hello-net

networks:
  hello-net:
    driver: bridge
